[package]
name = "day4"
version = "0.1.0"
authors = ["Florian Touya (deuzu) <florian.touya@pm.me>"]
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"
